commands:
  # Hora
  - comando:
    input:  Que horas são
    entidade: time
    acao: retornar_hora
  - comando:
    input:  Me diga as horas.
    entidade: time
    acao: retornar_hora
  # Data
  - comando:
    input:  Que dia é hoje?
    entidade: time
    acao: retornar_data
  - comando:
    input:  Data de hoje.
    entidade: time
    acao: retornar_data
  # Tempo
  - comando:
    input:  Previsão do tempo
    entidade: weather
    acao: retornar_temperatura
  - comando:
    input:  Como está o clima?
    entidade: weather
    acao: retornar_temperatura
  # Name
  - comando:
    input: Como você se chama
    entidade: name
    acao: retornar_nome
  - comando:
    input: Qual é seu nome?
    entidade: name
    acao: retornar_nome
  # Open
  - comando:
    input:  Abrir google
    entidade: open
    acao:
  - comando:
    input:  Abra youtube
    entidade: open
    acao:
